# Generated by Django 3.1.2 on 2020-10-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Xizmat nomi')),
                ('icon', models.CharField(max_length=150, verbose_name='Ikonkasi')),
            ],
        ),
    ]
