# Generated by Django 3.1.2 on 2020-11-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yangiliklar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Yangiliklar')),
                ('rasm', models.ImageField(blank=True, upload_to='Yangiliklar')),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ('title',),
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('title',), 'verbose_name': 'Xizmat', 'verbose_name_plural': 'Xizmatlar'},
        ),
    ]
