# Generated by Django 3.1.2 on 2020-11-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201102_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galereya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(blank=True, upload_to='Galereya')),
            ],
            options={
                'verbose_name': 'Galereya',
                'verbose_name_plural': 'Galereyalar',
                'ordering': ('rasm',),
            },
        ),
    ]
